# Generated by Django 4.1 on 2022-08-23 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_department_project_alter_employee_spouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.department'),
            preserve_default=False,
        ),
    ]
