# Generated by Django 4.1 on 2022-08-25 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_department_project_project_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='spouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.employee'),
        ),
    ]
