# Generated by Django 4.1 on 2022-08-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_employee_spouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_marriage',
            field=models.DateField(blank=True, null=True),
        ),
    ]
