# Generated by Django 4.1 on 2022-08-25 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_employee_date_of_marriage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='date_of_marriage',
        ),
    ]
