# Generated by Django 4.1 on 2022-08-26 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_employee_spouse'),
        ('app', '0012_employee_date_of_marriage'),
    ]

    operations = [
    ]
