# Generated by Django 4.1 on 2022-08-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_merge_20220826_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='department',
        ),
        migrations.AddField(
            model_name='employee',
            name='Job_Type',
            field=models.CharField(choices=[('full time', 'Full Time'), ('part time', 'Part Time')], default='full time', max_length=20),
        ),
    ]
