# Generated by Django 4.1 on 2022-08-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_works_on_employee_works_on_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works_on',
            name='duration',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
