# Generated by Django 4.1 on 2022-08-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_duration_works_on_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works_on',
            name='Duration',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
