# Generated by Django 4.1 on 2022-08-27 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_works_on_duration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Works_on',
            new_name='Workson',
        ),
    ]
